[package]
name = "pt"
version = "0.1.0"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"

[dependencies]
lean_cgmath = { git = "https://github.com/lambdaxymox/lean-cgmath" }
rand = "0.7.3"
