[package]
name = "pt"
version = "0.1.0"
authors = ["LambdaXymox <lambda.xymox@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lean_cgmath = { git = "https://github.com/lambdaxymox/lean-cgmath" }
